### ISSUE TITLE
thanks for your great work! by the way,how to place the dataset PACS ? can you illustrate it in README...

### ISSUE THREAD

**Issue by xinyiamazing** [lingeringlight/ALOFT#6]

**Comment by lingeringlight** [comment]
Hi, thanks for your interest in our work. We have updated the README to illustrate how to place the datasets for training and test. Let me know if you have any further questions.

**Comment by xinyiamazing** [comment]
Thanks for your reply! I just train the model by using PACS , but the results don't fit to the paper. I don't know which step i did wrong. Can you me some advice... My train log is below. Target domain is cartoon. 
[log.txt](https://github.com/lingeringlight/ALOFT/files/12259775/log.txt)

**Comment by xinyiamazing** [comment]
ohh, I know that! I didn't use the pretrained model. Because the pretrained model you provided is "gfnet-ti.pth", not the "gfnet-h-ti.pth".I can't run this code successfully by using "gfnet-ti.pth", because the model weights don't match to network.Can you provide the correct pretrained model (:
![screenshot_1](https://github.com/lingeringlight/ALOFT/assets/67252481/b56cfa7f-87ee-4508-8281-128a28156534)

**Comment by lingeringlight** [comment]
Hi, thank you for pointing this out. We have updated the [URL](https://drive.google.com/file/d/1Nrq5sfHD9RklCMl6WkcVrAWI5vSVzwSm/view) for "gfnet-h-ti.pth" in README. You can also download the pretrained model in [GFNet](https://github.com/raoyongming/GFNet).
